### ISSUE TITLE
Home page card view change and add popup for notices

### ISSUE THREAD

**Issue by Yathartha22** [shubham9411/notices-app#12]
Images should have a link rather than the whole image being displayed. Also this should also reflect back to `My Notices`. At present images are not shown in `MyNotices`.

I guess its easy-to-fix.

**Comment by shubham9411** [comment]
We'll be removing image from the home page and will add the attachment button to open them. 
- [x] Card changes
- [x] Attachments Button
- [x] Popup page with all the info of notice
