### ISSUE TITLE
Validity dates not properly shown

### ISSUE THREAD

**Issue by Yathartha22** [shubham9411/notices-app#14]
In `Create New Notice` section the validity dates are not properly displayed, only two months are available.
Also, `validity` should mean something, after the validity is over the notice should be displayed for end-user(This becomes the task of the backend :wink: ). We can have it displayed for admin in `My Notice section`.

**Comment by shubham9411** [comment]
Actually, after the validity is over the notice should *not* be displayed for end-user. 
Also a good-first-issue for you :wink:
